name: build-linux

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install glut
      run: sudo apt-get -y install freeglut3-dev
    - name: configure
      run: mkdir build-release && cd build-release && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: build
      run: cmake --build build-release
    - name: tests
      run: cd bin && ./KernelTests
